import Head from 'next/head'
import { Button, Card, CardGroup, Image, Header } from 'semantic-ui-react'
import Link from 'next/link'
import { client } from '../utils/shopify'
import styles from '../styles/Home.module.css'
import { encode, decode } from 'shopify-gid'

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CardGroup itemsPerRow={4}>
          {products.map(product => {
            const id = product.id.split('/');
            const lastArr = [id.length - 1]
            return (
              <Link href={`/product/${id[lastArr]}`}>
                <Card>
                  <Image src={product.images[0].src}></Image>
                  <Card.Content>
                    <Header>
                      {product.title}
                    </Header>
                  </Card.Content>
                </Card>
              </Link>
            )
          })}
        </CardGroup>
        <Button color='orange'>Orange</Button>
      </main>

    </div>
  )
}

export async function getServerSideProps() {
  const products = await client.product.fetchAll();

  return { props: { products: JSON.parse(JSON.stringify(products)) } }
}
